struct Solution;

impl Solution {
    fn index(c: char) -> i32 {
        match c {
            'a' => 1,
            'e' => 2,
            'i' => 3,
            'o' => 4,
            'u' => 5,
            _ => 0,
        }
    }
    pub fn longest_beautiful_substring(word: String) -> i32 {
        let word = word.chars().collect::<Vec<_>>();
        let (mut i, mut j) = (0i32, -1i32);
        let mut result = 0;
        while j < word.len() as i32 - 1 {
            j += 1;
            if j - i + 1 == 1 {
            } else if Self::index(word[j as usize]) - Self::index(word[j as usize - 1]) == 0
                || Self::index(word[j as usize]) - Self::index(word[j as usize - 1]) == 1
            {
            } else {
                i = j;
            }
            if word[i as usize] != 'a' {
                i += 1;
            } else if word[j as usize] == 'u' {
                result = result.max(j - i + 1);
            }
        }
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        assert_eq!(
            Solution::longest_beautiful_substring("aeiaaioaaaaeiiiiouuuooaauuaeiu".to_owned()),
            13
        );
        assert_eq!(
            Solution::longest_beautiful_substring("aeeeiiiioooauuuaeiou".to_owned()),
            5
        );
        assert_eq!(Solution::longest_beautiful_substring("a".to_owned()), 0);
        assert_eq!(Solution::longest_beautiful_substring("eueuiiuaeuuuoeeeuaeuiiuueoeeooaoaiaoooiiouiieouoeauaouuoueaaoueeauuiioiuoeiuuaiiuieaoaoiouaouuoeauiaeaeuuoeieeuoiaeoaeioouiuioeoeuooaaiiaeiiaaieoeuoeouaoaoeeeuoeaaeouiiaaeuuoueaeoiieeeuioaouuaeaiaoooooioieuoaaaueiooaaiaiaioueuaaaeeuooaoaaeeiiiuueuauaaooaoauiaaeaueueuieieeeeeoiieeueeeeeoaeeoaoauuuoeooeeeiuoiououeieeueoioiuuouoeeoeuieiuaiooeoiieouiiaeuoeaoeaeueeioeeoaieeiieaeueouaaaoauaeiaaooaueiuieeeueoiouiuiioauieueieuuueeeooeuouiuiaaoeioaauaaeaeoaeoueeoaouuuuioieuaaouioeaiouooeooioeeuuoiaoooueouieeeiiuuiaooueoeeiiieeuaiuuaiuuoaoeoouuueoeuaaeeaouoaeuiiieeeiiaueiuuoauuoeaeuuaoueeuooaoeuoieeaiauiaeuiiuaeaeoeiouaoaeaoouoeooiaaiioiuaaououueiioiauooaaiuuaauaeiiuauaoeuooauiaouuoiuuoieuiuueuuooeoeeiiuaueeueiuioeieoaoaoooeaeiuiuuaouooeueoaoioiuoaoooaoioeiiiuiuueeeuiiuioiiaeiaeoiaieuiaieaaoaaieouueeiueaooaooiuaiaoaueuoaoueuaiuuaaieiuauaeeaoooiuoeuuiiauuuuaauoieoeieiieeeeouioeuoeaoeiiaaoooeuioauiuioeaiauaieuoioaueoaiuuuoueueiiuaoieeeeiiaeeeioeeuaoiiieuuaaaeoauooauaeouiuuoaauueaeiaeioeiuoaiauaououaeaaoaooeiiueuiaieeuiieeuaueaeeeaeaeaeeoueeouioaiiiuueuiaioaeuoiiiaouoeooueooeioeeiiouuuoioaoeouuauieuiuoooaauoeoiiuiouiaeeoaioeuaaaouaoaueooeiauoueauauaeiiioeeuoiaoueeiioeaauiuouuoeiuoaiouoaiaoooeoaoouooeooioaoieaiuoouaaaauoiaueeeuooeouiouuouuueoooiuououaouieauieeiuoiieeaoiaoiueaioiiauuaoeaiaeoouuuiuaeaaaiiuieuoaiaoauaaoioauioiaeuaeuuoeaouioaiiuuooaeeueaouaaoaeaoieooaiuouuaueueiaaieoeouaaieeeioieoeuooouueiieaoieeueuaaieeeaueiooiaaoauuaaaaaeaoeioouuioauueoaoeuueueiieeeoeeaueiiuoaoeoieeeuieiuiaooouiaueeiiiouuuaauiuuoueaiiuoaieaoaaeoaueuuoaiaoeueeeaiaoioiaoooeuaueeaaoiouuioaaaiouoaoieaououaoeiaioeoeeeaeaaouaoeoeaioiaaoeeeueuioeoieaoioueoauoioiuaoaoaiouuoaeeaauiooiuueaaieoiuaiieouaoooeeoaiuoaeieouoauiiauoeeooeoieuuoaaaiaoiioiiueaoeueoieoaouoaiueaeeieiouiueeoauieioaeaeouuaoaoaiueeeuuaeauaouuiaueuiuaiueuoueiioiiaiaeouaaaoaoueuoueuaiouaaaououiaeuueuoouoaeuouuooeeoauiaooiiuaeieiaaooiuuoooooueaiiiaoouuuoiieaauaaiueuoooaaiuaieeeaoeieioeooeooeuaeuiueiueoioueaauiaoueaoiiieeeauuoeaaiaoooeeaiooieioiueeuieoiaiuoeuiooaouaueoeoaueuuooiaueoiuoeieieeaaiouiiioiooooiaoiaoeeuuiauuaeoeeaaeoiuuooiaeoiuoeoaeiuueiaeeeoiouoeieeaaoioaueieeuuioiaoeueooaeauieieiaiieeaieiaoaeaoiouuoeeaeeiaeaoiaueeoaioeeaouaeaoieeeueiuaueauuoiuoeueoiooiaoueeaaaaeaiiaeoaeaaoaaeuaaaeiaoeiueiieeuaiaaaoiiiueiiuoaeeooiuuiuooiuiiaoiiuueoaeuouiuaeuuaooiaaeeauouuioeauuoouiaeuueoiuieaiooauuuieiaeeoaiaoouoiauueaioauiuuuiuuuiaouaooeaoaieaieuaaoieieaeieuoiooiiiuaoaauaieeioiieuoaeuuuoiaeiaiuaeaoaaooaoaaiueiuaouiiuuieeaeauiaaaaeuaiiooaoiaueiieeuiaeieoiaeeuoieoieiaaoaoooauiiieioeaiiiiaiuiuueoeoeuoeuioaeaeeaioiiuuauoooieoeeieooiaauaiieaouiooioeoiaoaaaiauaeiuiaoeoaeaiuouieeeiieieieoaoeeaeaaiiieuaaeoouueauaooiauaaaooeuoueueaoiaiaaoeiueoeieeooueeueiueeoaeaeeueoaaaauuaueioouiioioiiuaiiauuueeueeouioooueaoieiueuueiueaoiouoiaeeueaeeioaoueeuieaeoeiuuiaueaieaoieoeiiuiiaiuauaaouauoueiououiuiioooeieooaieoeoiaiiuuoaeeauoieuoiuaaaaiioauaieoioieuauiiaoieueieeouaoiioaeoouaeeouoaiiioieoeiiouoaaioieieuoeiouiueioiuiaiuiuauuiiiueuiueaieuaeaioiuiaoauaioaoaeiiooiieeeeeoooooaieoauuieeauaoiiooaoaiaeieaiuooaoiauiuaoeaaeooueaiuuoioeieuoeieauueoaueieeaaueiauiaoauauuueuooouooeeuaoeeioiiuouiiaoeaaiuaaeouoiaaeieuiieeaeuaeuouaooieouaiiauoeeiuuieioueoeoiuuiuuoeiuiaieiouoeuoauuueouiaaaouiuuiuuaeiuooaeeeuuuouiiiiieiuaiueauuoouueaeaiiooeieoaoaoiauiiueeooooiuiaueuuuiaeaueiooaeeoiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuooooueieoeiuoiueuoooouaioooieuoueoaououiuiaaoaaieauoioioeiiuoouaeaieoiuiiooueoueaueueoauiiauaoieoeuiiuieueuoooeauoiueooiieeieieauaouoeoiiuaoiooeuaaiaouiaueiaueaauoooieauuiiaueuiioaeeiuiioiiuuiuuueiouoiaoeaiuiiaiooaaiauiaoooaeuuaaaueaoeiuiooiioiiaiuoeuoueouuaaiiioeooauueoaoeaeaaoaouuieaueuoueiooiiuiuuuouauaiauaiueauaa".to_owned()), 3827);
    }
}
